local cursor = require("cursor_lock.cursor")

go.property("acquire_input_focus", true)
go.property("click_action_id", hash("touch"))
go.property("unlock_action_id", hash("key_esc"))

local function lock_cursor()
    if not cursor.locked then
        if html5 then
            cursor_lock_ext.html5_request_cursor_lock()
        else
            cursor.locked = true
            cursor_lock_ext.glfw_mouse_lock()
        end
    end
end

local function unlock_cursor()
    if cursor.locked then
        if html5 then
            cursor_lock_ext.html5_exit_cursor_lock()
        else
            cursor.locked = false
            cursor_lock_ext.glfw_mouse_unlock()
        end
    end
end

function init(self)
    if self.acquire_input_focus then
        msg.post(".", "acquire_input_focus")
    end
    
    cursor.locked = false
    cursor_lock_ext.glfw_mouse_unlock()

    --[[if html5 then
        cursor_lock_ext.html5_on_click(function()
            if not cursor.locked then
                cursor_lock_ext.html5_request_cursor_lock()
            end
        end)
    end]]
end

function final(self)
    cursor.locked = false
    cursor_lock_ext.glfw_mouse_unlock()

    if html5 then
        cursor_lock_ext.html5_on_click(nil)
    end
end

function update(self, dt)
    if html5 then
        cursor.locked = cursor_lock_ext.html5_cursor_locked()
    end
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
    --[[if html5 then
        if cursor.locked and action_id == self.unlock_action_id and action.released then
            unlock_cursor()

            return true
        end
    else
        if action_id == self.unlock_action_id and action.released then
            local skip_events = cursor.locked
            unlock_cursor()

            return skip_events
        elseif action_id == self.click_action_id and action.released then
            local skip_events = cursor.locked
            lock_cursor()

            return skip_events
        end
    end]]
    if action.pressed then
        if action_id == self.click_action_id then
            lock_cursor()
        elseif action_id == self.unlock_action_id then
            unlock_cursor()
        end
    end
end
